name: Build with Script and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Build Docker image using build script
        run: ./build.sh docker -t ezbookkeeping:release

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag ezbookkeeping:release ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker tag ezbookkeeping:release ghcr.io/${{ github.repository }}:latest
          
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest
